version: '3'
services:
  postgres:
    image: postgres:14
    ports:
      - "${DB_PORT}:5432"
    container_name: bookinghotels-postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

#  book-service-app:
#    build: .
#    container_name: bookinghotels-app
#    depends_on:
#      - postgres
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
#      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
#      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
#      SERVER_PORT: ${APP_PORT}
#    ports:
#      - "${APP_PORT}:${APP_PORT}"