spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:bookservicedb
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: 'create-drop'
    generate-ddl: true
    show-sql: true

server:
  port: 8890

#springdoc:
#  swagger-ui:
#    enabled: true
#  api-docs:
#    enabled: true