spring:
  sql:
    init:
      mode: ALWAYS
  data:
    mongodb:
      uri: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/${MONGO_INITDB_DATABASE}?authSource=admin
  main:
    allow-bean-definition-overriding: true
  kafka:
    bootstrap-servers: kafka:${KAFKA_PORT}
#  h2:
#    console:
#      enabled: true
  datasource:
    url: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
#    hikari:
#      schema: app_schema
#      connection-init-sql: CREATE SCHEMA IF NOT EXISTS app_schema;
#      connection-timeout: 10000

  jpa:
    hibernate:
      ddl-auto: 'create-drop'
    generate-ddl: true
    show-sql: true

app:
  security:
    type: db
  kafka:
    registrationUserTopic: "registration-user-topic"
    registrationUserGroupId: "registration-user-group-id"
    bookingRoomTopic: "booking-room-topic"
    bookingRoomGroupId: "booking-room-group-id"

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG