spring:
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/appdatabase?authSource=admin
  main:
    allow-bean-definition-overriding: true
  kafka:
    bootstrap-servers: localhost:29092
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:8432/app_schema
    username: postgres
    password: postgres
    hikari:
      schema: app_schema
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS app_schema;
      connection-timeout: 10000

  jpa:
    hibernate:
      ddl-auto: 'update'
    generate-ddl: true
    show-sql: true

server:
  port: 8890

app:
  security:
    type: db
  kafka:
    registrationUserTopic: "registration-user-topic"
    registrationUserGroupId: "registration-user-group-id"
    bookingRoomTopic: "booking-room-topic"
    bookingRoomGroupId: "booking-room-group-id"