spring:
  sql:
    init:
      mode: ALWAYS
  data:
    mongodb:
      uri: mongodb://root:root@mongodb:27017/appdatabase?authSource=admin
  main:
    allow-bean-definition-overriding: true
  kafka:
    bootstrap-servers: kafka:9092
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: postgres
    password: 3101

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true

app:
  security:
    type: db
  kafka:
    registrationUserTopic: "registration-user-topic"
    registrationUserGroupId: "registration-user-group-id"
    bookingRoomTopic: "booking-room-topic"
    bookingRoomGroupId: "booking-room-group-id"

server:
  port: 8890

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG